INSERT INTO ROOM_TYPE (type_id, room_type, room_price, room_details) VALUES ('1', 'Sigle', 557, 'A room assigned to one person. May have one or more beds.');
INSERT INTO ROOM_TYPE (type_id, room_type, room_price, room_details) VALUES ('2', 'Double', 146, 'A room assigned to two people. May have one or more beds.');
INSERT INTO ROOM_TYPE (type_id, room_type, room_price, room_details) VALUES ('3', 'Triple', 303, 'A room assigned to three people. May have two or more beds.');
INSERT INTO ROOM_TYPE (type_id, room_type, room_price, room_details) VALUES ('4', 'Quad', 939, 'A room assigned to four people. May have two or more beds.');
INSERT INTO ROOM_TYPE (type_id, room_type, room_price, room_details) VALUES ('5', 'Queen', 385, 'A room with a queen-sized bed. May be occupied by one or more people.');
INSERT INTO ROOM_TYPE (type_id, room_type, room_price, room_details) VALUES ('6', 'Twin', 330, 'A room with two beds. May be occupied by one or more people.');
INSERT INTO ROOM_TYPE (type_id, room_type, room_price, room_details) VALUES ('7', 'Double-double', 110, 'A room with two double (or perhaps queen) beds. May be occupied by one or more people.');
INSERT INTO ROOM_TYPE (type_id, room_type, room_price, room_details) VALUES ('8', 'Studio', 597, 'A room with a studio bed – a couch that can be converted into a bed.');
INSERT INTO ROOM_TYPE (type_id, room_type, room_price, room_details) VALUES ('9', 'Master Suite', 841, 'A parlour or living room connected to one or more bedrooms.');
INSERT INTO ROOM_TYPE (type_id, room_type, room_price, room_details) VALUES ('10','Junior Suite', 734, 'A single room with a bed and sitting area.');
